/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;

/**
 *
 * @author gu_si
 */
public class TelaDeCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCadastro
     */
    public TelaDeCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCadEmail = new javax.swing.JTextField();
        txtCadNome = new javax.swing.JTextField();
        txtCadSenha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btSetCadastro = new javax.swing.JButton();
        btcadastroToLogin = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tela de cadastro.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(910, 558));
        getContentPane().setLayout(null);
        getContentPane().add(txtCadEmail);
        txtCadEmail.setBounds(500, 250, 320, 60);
        getContentPane().add(txtCadNome);
        txtCadNome.setBounds(500, 340, 320, 60);
        getContentPane().add(txtCadSenha);
        txtCadSenha.setBounds(500, 432, 320, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tela de cadastro.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 910, 570);

        btSetCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btSetCadastro);
        btSetCadastro.setBounds(530, 513, 240, 50);

        btcadastroToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastroToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btcadastroToLogin);
        btcadastroToLogin.setBounds(700, 140, 72, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcadastroToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastroToLoginActionPerformed
        // TODO add your handling code here:
        new TelaDeLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcadastroToLoginActionPerformed

    private void btSetCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetCadastroActionPerformed
        // TODO add your handling code here:
        String email, nome, senha;
        email = txtCadEmail.getText();
        nome = txtCadNome.getText();
        senha = txtCadSenha.getText();
        
        UsuarioDTO novoUsuariodto = new UsuarioDTO();
        novoUsuariodto.setEmail(email);
        novoUsuariodto.setNome(nome);
        novoUsuariodto.setSenha(senha);
        
        UsuarioDAO novoUsuariodao = new UsuarioDAO();
        novoUsuariodao.cadastrarUsuario(novoUsuariodto);
        
        new TelaDeLogin().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btSetCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSetCadastro;
    private javax.swing.JButton btcadastroToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCadEmail;
    private javax.swing.JTextField txtCadNome;
    private javax.swing.JTextField txtCadSenha;
    // End of variables declaration//GEN-END:variables
}
