/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;

import DAO.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author gu_si
 */
public class TelaDeFinalizarCompra2 extends javax.swing.JFrame {

     Connection conn = null;
    PreparedStatement pstm = null;
    ResultSet rs = null;
    
    public void ProdutoEstoque2() {

        String sql = "update produtos SET estoque_produto = estoque_produto - 1  where id_produto = 1;";
       conn = new Conexao().conectaBD();

    try {
            pstm = conn.prepareStatement(sql);  
            pstm.execute();
            pstm.close();
         
            

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ProdutoDAO" + erro);
        }

    }
    /**
     * Creates new form TelaDeFinalizarCompra2
     */
    public TelaDeFinalizarCompra2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btcancelcompra2 = new javax.swing.JButton();
        btfinalteclado = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/compra2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 970, 770);

        btcancelcompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelcompra2ActionPerformed(evt);
            }
        });
        getContentPane().add(btcancelcompra2);
        btcancelcompra2.setBounds(540, 240, 240, 100);

        btfinalteclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfinaltecladoActionPerformed(evt);
            }
        });
        getContentPane().add(btfinalteclado);
        btfinalteclado.setBounds(540, 113, 250, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btfinaltecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfinaltecladoActionPerformed
        // TODO add your handling code here:
        ProdutoEstoque2();
        
        new TelaDeCompraFinalizada().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btfinaltecladoActionPerformed

    private void btcancelcompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelcompra2ActionPerformed
        // TODO add your handling code here:
        new TelaDeCompra().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcancelcompra2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeFinalizarCompra2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelcompra2;
    private javax.swing.JButton btfinalteclado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
