/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;

import DAO.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author gu_si
 */
public class TelaDeFinalizarCompra6 extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pstm = null;
    ResultSet rs = null;
    
    public void ProdutoEstoque6() {

        String sql = "update produtos SET estoque_produto = estoque_produto - 1  where id_produto = 6;";
       conn = new Conexao().conectaBD();

    try {
            pstm = conn.prepareStatement(sql);  
            pstm.execute();
            pstm.close();
         
            

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ProdutoDAO" + erro);
        }

    /**
     * Creates new form TelaDeFinalizarCompra3
     */
    }

    /**
     * Creates new form TelaDeFinalizarCompra6
     */
    public TelaDeFinalizarCompra6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btcancel6 = new javax.swing.JButton();
        btcomprafinal6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/compra6.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1160, 760);

        btcancel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancel6ActionPerformed(evt);
            }
        });
        getContentPane().add(btcancel6);
        btcancel6.setBounds(550, 220, 220, 110);

        btcomprafinal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcomprafinal6ActionPerformed(evt);
            }
        });
        getContentPane().add(btcomprafinal6);
        btcomprafinal6.setBounds(540, 100, 240, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcomprafinal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcomprafinal6ActionPerformed
        // TODO add your handling code here:
        ProdutoEstoque6();
        new TelaDeCompraFinalizada().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcomprafinal6ActionPerformed

    private void btcancel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancel6ActionPerformed
        // TODO add your handling code here:
        new TelaDeCompra().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcancel6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeFinalizarCompra6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancel6;
    private javax.swing.JButton btcomprafinal6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
