/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;

//import DAO.ProdutoDAO;
import DTO.ProdutoDTO;
import java.sql.*;
import DAO.Conexao;
import javax.swing.JOptionPane;

/**
 *
 * @author gu_si
 */
public class TelaDeFinalizarCompra1 extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pstm = null;
    ResultSet rs = null;
    
    public void ProdutoEstoque1() {

        String sql = "update produtos SET estoque_produto = estoque_produto - 1  where id_produto = 2;";
       conn = new Conexao().conectaBD();

    try {
            pstm = conn.prepareStatement(sql);  
            pstm.execute();
            pstm.close();
         
            

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ProdutoDAO" + erro);
        }

    }
    
    //ProdutoDTO novoEstoquedto = new ProdutoDTO();
        //novoEstoquedto.setEstoque_produto(estoque_produto);
        
       // ProdutoDAO novoEstoquedao = new ProdutoDAO();
        //novoEstoquedao.ProdutoEstoque(novoEstoquedto);

    /**
     * Creates new form TelaDeFinalizarCompra
     */
    public TelaDeFinalizarCompra1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btcancelcompra1 = new javax.swing.JButton();
        btFinalMonitor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/compra1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setName(""); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 1270, 760);

        btcancelcompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelcompra1ActionPerformed(evt);
            }
        });
        getContentPane().add(btcancelcompra1);
        btcancelcompra1.setBounds(550, 200, 230, 100);

        btFinalMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalMonitorActionPerformed(evt);
            }
        });
        getContentPane().add(btFinalMonitor);
        btFinalMonitor.setBounds(550, 60, 240, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFinalMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalMonitorActionPerformed
        // TODO add your handling code here:
        ProdutoEstoque1();
        //ProdutoDTO novoEstoquedto = new ProdutoDTO();
        //novoEstoquedto.setEstoque_produto(estoque_produto);
        
       // ProdutoDAO novoEstoquedao = new ProdutoDAO();
        //novoEstoquedao.ProdutoEstoque(novoEstoquedto);
      
 
        new TelaDeCompraFinalizada().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btFinalMonitorActionPerformed

    private void btcancelcompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelcompra1ActionPerformed
        // TODO add your handling code here:
        new TelaDeCompra().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcancelcompra1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalizarCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeFinalizarCompra1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalMonitor;
    private javax.swing.JButton btcancelcompra1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    void setVIsible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
