/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;

import java.sql.*;
import DAO.Conexao;

/**
 *
 * @author gu_si
 */
public class TelaDeCompra extends javax.swing.JFrame {

    
  
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form TelaDeCompra
     */
    public TelaDeCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaDeCompra = new javax.swing.JLabel();
        btcompra1 = new javax.swing.JButton();
        btcompra2 = new javax.swing.JButton();
        btcompra3 = new javax.swing.JButton();
        btcompra4 = new javax.swing.JButton();
        btcompra5 = new javax.swing.JButton();
        btcompra6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(null);

        TelaDeCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/teladecompra.png"))); // NOI18N
        getContentPane().add(TelaDeCompra);
        TelaDeCompra.setBounds(0, 0, 910, 800);

        btcompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompra1ActionPerformed(evt);
            }
        });
        getContentPane().add(btcompra1);
        btcompra1.setBounds(50, 200, 180, 140);

        btcompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompra2ActionPerformed(evt);
            }
        });
        getContentPane().add(btcompra2);
        btcompra2.setBounds(290, 223, 230, 110);

        btcompra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompra3ActionPerformed(evt);
            }
        });
        getContentPane().add(btcompra3);
        btcompra3.setBounds(600, 213, 140, 140);

        btcompra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompra4ActionPerformed(evt);
            }
        });
        getContentPane().add(btcompra4);
        btcompra4.setBounds(50, 460, 180, 140);

        btcompra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompra5ActionPerformed(evt);
            }
        });
        getContentPane().add(btcompra5);
        btcompra5.setBounds(320, 473, 170, 140);

        btcompra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompra6ActionPerformed(evt);
            }
        });
        getContentPane().add(btcompra6);
        btcompra6.setBounds(610, 473, 120, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompra1ActionPerformed
        // TODO add your handling code here:
        new TelaDeFinalizarCompra1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcompra1ActionPerformed

    private void btcompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompra2ActionPerformed
        // TODO add your handling code here:
         new TelaDeFinalizarCompra2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcompra2ActionPerformed

    private void btcompra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompra3ActionPerformed
        // TODO add your handling code here:
         new TelaDeFinalizarCompra3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcompra3ActionPerformed

    private void btcompra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompra4ActionPerformed
        // TODO add your handling code here:
         new TelaDeFinalizarCompra4().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcompra4ActionPerformed

    private void btcompra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompra5ActionPerformed
        // TODO add your handling code here:
         new TelaDeFinalizarCompra5().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcompra5ActionPerformed

    private void btcompra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompra6ActionPerformed
        // TODO add your handling code here:
         new TelaDeFinalizarCompra6().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcompra6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaDeCompra;
    private javax.swing.JButton btcompra1;
    private javax.swing.JButton btcompra2;
    private javax.swing.JButton btcompra3;
    private javax.swing.JButton btcompra4;
    private javax.swing.JButton btcompra5;
    private javax.swing.JButton btcompra6;
    // End of variables declaration//GEN-END:variables
}
